### ISSUE TITLE
Project duplicate creates issues and blocks editing

### ISSUE THREAD

**Issue by RonMath** [Giveth/giveth-next#106]
## 📋 Anything to add?
Unfortunately I managed to add a project two times, 
https://giveth.io/project/positiveblockchain.io/
That creates issues obviously, even that one project was deactivated.

To avoid, it shouldn't  be possible to add an identical project twice

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by laurenluz** [comment]
Hi @RonMath - thanks for your feedback! We have updated the site so now it should not be possible to have two projects with an identical URL - even if the projects have the same name, that will be different. It is also not possible on giveth.io to create the two projects with the same recipient address.

Did you already try to deactivate the duplicate project?

@mateodaza can you help with this?

**Comment by RamRamez** [comment]
I have two projects with the same title and same slug!
How is it possible?

I think edit project is buggy for same title projects.

![image](https://user-images.githubusercontent.com/73441857/132948564-75bf29c5-712c-4380-aa4b-852c5505255c.png)

**Comment by RamRamez** [comment]
> I have two projects with the same title and same slug!
> How is it possible?
> 
> I think edit project is buggy for same title projects.
> 
> ![image](https://user-images.githubusercontent.com/73441857/132948628-ffa4ace4-5c6e-49c2-9067-e793d316cf36.png)

@MoeNick I think this is an important issue.

**Comment by MoeNick** [comment]
Just assigned it to Mohammad and Mateo to take a loook.

**Comment by mateodaza** [comment]
> I have two projects with the same title and same slug!
> How is it possible?
> 
> I think edit project is buggy for same title projects.
> 
> ![image](https://user-images.githubusercontent.com/73441857/132948628-ffa4ace4-5c6e-49c2-9067-e793d316cf36.png)

Did you remove it? I can't see it 
![image](https://user-images.githubusercontent.com/18689480/133092880-7993c930-ce8b-4ba2-8777-622c4141b3c1.png)

**Comment by RamRamez** [comment]
@mateodaza No I didn't remove them. They are still in "my projects" menu

![image](https://user-images.githubusercontent.com/73441857/133146498-dd605337-78b4-4d8d-9da8-0f7ac8e181ae.png)

**Comment by mateodaza** [comment]
@RamRamez you're right, I only fixed on public project list. gotcha

**Comment by RamRamez** [comment]
I made two projects with the same title "Ram second metamask"

The first one's slug was "ram-second-metamask" and the second one's slug was "ram-second-metamask-1".

But after editing one of them, both slugs became similar.

**Comment by mohammadranjbarz** [comment]
@MoeNick  I've fixed this issue in https://github.com/Giveth/impact-graph/pull/139
and it's good to see https://github.com/Giveth/impact-graph/issues/113#issuecomment-923809564

I think this issue is resolved already

**Comment by laurenluz** [comment]
uh ohhhhh I broke it testing it and didn't take enough screenshots.

Basically, I made a new project call "my perfect project" (there was already one I had made before). the project was created fine, and then when I clicked "view my project" from the "high five" page, it send me back to the original "my perfect project" (not the new one I just made).

you can see the two that exist here:

![image](https://user-images.githubusercontent.com/75490971/135933975-681158b4-84b7-4bfe-9563-83ada3ed6ebb.png)

Same thing happens when I click the new "my perfect project" from "my projects"

clicking this:
![image](https://user-images.githubusercontent.com/75490971/135934051-97de8029-ece6-4906-b316-3e830eeac2aa.png)

brings me here:
![image](https://user-images.githubusercontent.com/75490971/135934111-c1a87986-496a-41c5-9381-c25f785bc6e0.png)

FYI if I click on the original project (with the bird)... it also takes me to the bird version...

seems I can't open the new version of "my perfect project"

**Comment by mateodaza** [comment]
Both projects were saved with the same slug "my-perfect-project-1"
@mohammadranjbarz you have any idea why this happened, maybe it's an old case?

**Comment by mohammadranjbarz** [comment]
> Both projects were saved with the same slug "my-perfect-project-1" @mohammadranjbarz you have any idea why this happened, maybe it's an old case?

Yeah we had a problem on checking slug uniqueness that is fixed already
https://github.com/Giveth/impact-graph/issues/113#issuecomment-923809564

**Comment by MoeNick** [comment]
@divine-comedian appriciate if you can jump in testing.

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
This issue made problems in this flow:
@divine-comedian  @MoeNick 
there was a project with slug named `x` then you could create another project with slug `x`
after the user wants to edit one of the projects sometimes the other one would be edited

so I think if we don't have this problem we can close this issue and create another one for preventing repetitive names
