### ISSUE TITLE
view (traceable) projects in givethio with links to trace.giveth.io

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#125]
Me as a user want to see the list of traceable projects on project list in giveth.io so I can see their details on trace.

**Description:**
1- Traceable project should have a badge on their card. 

2- The list of traceable project can get by this query: 
https://feathers.beta.giveth.io/campaigns?verified=true

3- They should have hyperlinks in new tab in this format: 
https://trace.giveth.io/campaign/{campaignSlug}

4- They can be filtered by "traceable" at top. 

**Success Criteria:**
1- User go to project page
2- See list of all project and traceable projects 
3- Filter by traceable and see the list. 
4- click on any of them, should redirect the user to new page to trace.giveth.io

**Comment by divine-comedian** [comment]
testing on `next.giveth.io`

traceable projects show up on giveth.io, I click the link and it takes me to the slug on trace.giveth.io
this however brings a 404 error since it is a testing project and only exists on develop.giveth.io

![image](https://user-images.githubusercontent.com/67759413/125634446-14024eb5-5f88-4129-b818-d0c163d8d4f0.png)

is this okay @MoeNick  or should we have a more intelligent design to make testing the user flow easier?

**Comment by mateodaza** [comment]
This is because the projects shown are from the dev environment but I'm pointing to the live instance of trace.

I just have to change it and that's it. Was waiting for trace to be fully ready, I can do it soon

**Comment by MoeNick** [comment]
We have deploy yesterday, maybe mateo should change the url and list updated. 
@mateodaza @divine-comedian

**Comment by divine-comedian** [comment]
Okay so is this the desired flow? Do i need to do more testing?

**Comment by MoeNick** [comment]
#137
@divine-comedian let it be here, then test it with this one.

**Comment by laurenluz** [comment]
this is working fine on live
