### ISSUE TITLE
When Switch account the sign in ux is implemented in a way that when user clicks on sign in two requests appears to sign

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#428]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/143938958-2e49f604-6e3d-4993-a284-d0205a76e648.png)
![image](https://user-images.githubusercontent.com/53400757/143939267-9ebdcb5a-5f12-4bf1-a038-bc9bd2ab6e7f.png)

**Comment by mateodaza** [comment]
@RamRamez I think the work you're doing with the authentication relates to this, can you take a look?

**Comment by RamRamez** [comment]
Related to PR #465 
@DonnaOftadeh Please check it

**Comment by divine-comedian** [comment]
with the new wallet flow I can see that I am only prompted once on the UI to sign in to my account - 
![image](https://user-images.githubusercontent.com/67759413/146972783-340cfb3c-708c-49e9-a5c7-7ad443d2fae1.png)

one signature transaction is sent only (MetaMask) 

with the new wallet and address account relation and the updated navbar I think this issue is resolved
