### ISSUE TITLE
Add Support Page

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#49]
Support page added - please review.

Reachable via github popup or directly at the route `/support`

**Comment by WhyldWanderer** [comment]
This page will be replacing the current contact page correct? And you sould access it by clicking this link in the footer...

![image](https://user-images.githubusercontent.com/74267818/121401259-c023cd00-c915-11eb-869b-9719517c8f14.png)

**Comment by laurenluz** [comment]
this is from https://github.com/Giveth/giveth-2/issues/830 right?

**Comment by WhyldWanderer** [comment]
yes

**Comment by WhyldWanderer** [comment]
This seems to be working properly except that the form is being opened in the same tab instead of a pop up window.

It would be much friendlier for the user to be able to perform multiple actions such as requesting a feature AND asking a question if they didnt need to leave the page to fill out the quick form.

**Comment by laurenluz** [comment]
this will be done once https://github.com/Giveth/giveth-next/issues/89 goes through, moving to done

**Comment by WhyldWanderer** [comment]
It might mot be a big deal but I think we should change the text under the question section...

Right now it reads "Do you have a specific question or a general inquiry?"
![image](https://user-images.githubusercontent.com/74267818/122295953-0f8a7000-ceb7-11eb-824e-f870c1acb247.png)

I think we should change it to "Do you have a specific question or a general inquiry that requires a response?"
This way the user knows that they will get an answer since the other options do not ask for an email.

What do you guys think? @laurenluz @mateodaza ?

**Comment by laurenluz** [comment]
agreed! @WhyldWanderer
