### ISSUE TITLE
Campaigns Archived and Verified status for launch. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#493]
Spreadsheet is finalized by @WhyldWanderer and @mohammadranjbarz has access over it. 
We have to:
1- Make finale statuses in trace db
2- relate the Campaigns that have related projects on io

**Comment by mohammadranjbarz** [comment]
@MoeNick  It's done

**Comment by WhyldWanderer** [comment]
I can see that all of the Campaigns that needed to be archived are now archived.

Question: Dont we need to make it so that no new campaigns can be created unless they first create a project on io and then migrate it to TRACE? Has this been done?

Im not sure how to check the status of the database to see if they are 'verified' or not... to ensure that donors to these campaigns will receive GIVbacks for their donations to any Campaign on TRACE.

**Comment by MoeNick** [comment]
> I can see that all of the Campaigns that needed to be archived are now archived.
> 
> Question: Dont we need to make it so that no new campaigns can be created unless they first create a project on io and then migrate it to TRACE? Has this been done?
> 
> Im not sure how to check the status of the database to see if they are 'verified' or not... to ensure that donors will receive GIVbacks for their donations to any Campaign on TRACE.

Good point @WhyldWanderer 
@mohammadranjbarz can we remove campaign creation? After launch is going to be io first. 
and about verified status I think we don't have bandwith to show it but we can do it offline for you.

**Comment by WhyldWanderer** [comment]
I think you could maybe just link the "Start a Campaign" button to this documentation:
https://docs.giveth.io/dapps/makeTraceableProject

**Comment by MoeNick** [comment]
> I think you could maybe just link the "Start a Campaign" button to this documentation: https://docs.giveth.io/dapps/makeTraceableProject
  
We can put "Make your project traceable" in the Verified projects. ideas?

**Comment by WhyldWanderer** [comment]
> We can put "Make your project traceable" in the Verified projects. ideas?

Due to various reasons we are not actively promoting that projects become traceable at this time so I would leave that out.
Once a project becomes verified, they receive an email inviting them to upgrade to a campaign on TRACE.

The current things that keep us from promoting upgrading a campaign to TRACE are:
- mainnet gas fees are expensive.. and you would need to deposit the funds from your io wallet directly into your trace campaign in order to delegate them.
 - It is not compatible with xDai yet -- you would need to bridge any xDai donations from your giveth.io project wallet to mainnet in order to delegate them on trace.
 - the 300 dollar minimum to withdraw makes a bad user experience for small projects that receive small donations
 
 
 This being said, I think it is okay for users to explore their options and if a user wants to create a new campaign on TRACE we can link them to the documentation that shows them how to do it.

**Comment by MoeNick** [comment]
Thanks @WhyldWanderer 
I address limiting create campaign in another issue and will close this.
