### ISSUE TITLE
Update Join.giveth.io with Community Resources AND Info

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-next#50]
Per [convo in #communications channel on Discord](https://discordapp.com/channels/679428761438912522/790268394251354143/834869989868961833)
Revise Join page to present more information and resources including those in Docs, Medium and Twitter etc!

![image](https://user-images.githubusercontent.com/39466970/115789858-a71d8780-a37a-11eb-8e6d-44bf8e66cd01.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by laurenluz** [comment]
@geleeroyale

**Comment by MoeNick** [comment]
@geleeroyale and @mateodaza .... 
Can we assign it to @RamRamez ?

**Comment by geleeroyale** [comment]
Now I remember - all these changes are basically changes in the CMS or content in the code. When I had the call with @laurenluz I showed her how to make those changes.

I can handle this issue for now because I know my way around the CMS - thanks @RamRamez, sure there are more interesting issues you can tackle.

**Comment by geleeroyale** [comment]
Still need to do the footer links - rest is up on mateo-mig

**Comment by divine-comedian** [comment]
footer links are updated on `next.giveth.io`
all the links work and go to where they are supposed to!

![image](https://user-images.githubusercontent.com/67759413/125635921-7aad1cb2-47e4-4d32-8fd6-015bf7e0a760.png)
