### ISSUE TITLE
Donations not showing up

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#626]
One of my donations isn't showing in "my donations" or on the project page...
here's the 

tx: https://blockscout.com/xdai/mainnet/tx/0x3f14c65500ecb1a890c9884c31c279632367e2faf332c108ea11eaa176d77c2d

**Comment by MoeNick** [comment]
Did it resolved? 
Would u pls relate it to the PR?

**Comment by aminlatifi** [comment]
> Did it resolved? Would u pls relate it to the PR?

The entry was created for this donation had incorrect value for `projectId` and `userId`. It was probably created manually and the values were field instead of each other.

However, the reason behind missing entities like this is not clear yet. We don't have any clue and there isn't anything recorded in log records.

I and @mohammadranjbarz deduced that the only temporary solution is to add segment/sentry log around the logics in both front-end and back-end in order to have some valuable information next time it happens
